const books=[{title:'The Art of Stillness',author:'Pico Iyer',chapters:['An introduction','Where we find ourselves','The gift of nothing','A wider view']},{title:'Braiding Sweetgrass',author:'Robin Wall Kimmerer',chapters:['Skywoman falling','The council of pecans','The grammar of animacy']},{title:'The Book of Tea',author:'Kakuzō Okakura',chapters:['The cup of humanity','The schools of tea','Taoism and Zennism']}];
let activeBook=0,activeChapter=0,activePage=0,textSize=19,zoom=1;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const copy=[`<p><span class="drop">W</span>e all know the sensation: the day opens before us and, before we have noticed it, has already slipped away. A thought arrives, delicate as a bird on a windowsill. The invitation is not to hold it, but to make room for it.</p>`,`<p>Stillness is not an absence of movement. It is the small, clear space in which we can hear our own lives again. It asks for nothing more elaborate than a moment of attention.</p>`,`<img class="book-image" alt="A quiet landscape illustration" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1100' height='600'%3E%3Crect width='100%25' height='100%25' fill='%23d4b994'/%3E%3Cpath d='M0 430 Q200 220 430 390 T820 300 T1100 350V600H0Z' fill='%234f766b'/%3E%3Ccircle cx='800' cy='160' r='75' fill='%23f6dfad'/%3E%3Cpath d='M0 490 Q260 390 550 490 T1100 430V600H0Z' fill='%233c574e'/%3E%3C/svg%3E"/>`,`<p>To read is to participate in a private act of hospitality. We welcome another mind across distance and time, and in that meeting discover a little more of our own.</p>`];
function renderLibrary(){const grid=$('#bookGrid');grid.innerHTML='';books.forEach((book,i)=>{const n=$('#bookCardTemplate').content.cloneNode(true);n.querySelector('.cover-title').textContent=book.title;n.querySelector('.cover-author').textContent=book.author;n.querySelector('.book-title').textContent=book.title;n.querySelector('.book-author').textContent=book.author;n.querySelector('.book-cover').onclick=()=>openBook(i);n.querySelector('.more').onclick=e=>{e.stopPropagation();if(confirm(`Remove “${book.title}” from your shelf?`)){books.splice(i,1);renderLibrary()}};grid.append(n)});$('#bookCount').textContent=`${books.length} book${books.length!==1?'s':''}`}
function openBook(i){activeBook=i;activeChapter=0;activePage=0;$('#libraryView').classList.add('hidden');$('#readerView').classList.remove('hidden');$('#bookCrumb').textContent=books[i].title;renderChapter();}
function pageLimits(){const page=$('#page'),second=$('#pageTwo'),copy=$('#readerCopy'),title=$('#chapterTitle'),style=getComputedStyle(page),top=parseFloat(style.paddingTop)||0,bottom=parseFloat(style.paddingBottom)||0,restHeight=innerWidth<=600?page.clientHeight:second.clientHeight,restore=title.innerHTML;if(!title.textContent.trim())title.innerHTML=(books[activeBook]?.chapters[activeChapter]||'Chapter').replace(' ','<br>');const first=Math.max(80,page.clientHeight-copy.offsetTop-bottom);title.innerHTML=restore;return {first,rest:Math.max(80,restHeight-top-bottom),width:copy.clientWidth}}
function escapeHtml(text){const node=document.createElement('span');node.textContent=text;return node.innerHTML}
function splitTextElement(element,limit,fits){const text=(element.textContent||'').trim();if(!text)return [element.outerHTML];const shell=element.cloneNode(false),open=shell.outerHTML.replace(/<\/[^>]+>$/,''),close=`</${element.tagName.toLowerCase()}>`,words=text.split(/\s+/),parts=[],chunk=[];for(const word of words){chunk.push(word);const candidate=open+escapeHtml(chunk.join(' '))+close;if(!fits(candidate,limit)&&chunk.length>1){chunk.pop();parts.push(open+escapeHtml(chunk.join(' '))+close);chunk.length=0;chunk.push(word)}}if(chunk.length)parts.push(open+escapeHtml(chunk.join(' '))+close);return parts}
function pagesFor(html){const source=document.createElement('div');source.innerHTML=html;const limits=pageLimits(),probe=document.createElement('div');probe.className='reader-copy page-probe';probe.style.width=`${limits.width}px`;document.body.append(probe);const fits=(markup,limit)=>{probe.innerHTML=markup;return probe.scrollHeight<=limit};const pages=[],current=[];let pageIndex=0,limit=limits.first;const flush=()=>{if(current.length){pages.push(current.join(''));current.length=0;pageIndex++;limit=limits.rest}};for(const child of [...source.children]){let pieces=[child.outerHTML];if(!fits(pieces[0],limit)&&child.matches('p,div,blockquote,li,h1,h2,h3,h4,h5,h6'))pieces=splitTextElement(child,limit,fits);for(const piece of pieces){if(current.length&&!fits(current.join('')+piece,limit))flush();if(!fits(piece,limit)&&current.length)flush();current.push(piece)}}flush();probe.remove();return pages.length?pages:['<p>&nbsp;</p>']}
function renderChapter(){let b=books[activeBook],chapter=b.chapters[activeChapter],html=b.content?.[activeChapter]||copy.map((x,i)=>i===0?x:activeChapter%2===i%2?x:'').join('');$('#tocBookTitle').textContent=b.title;$('#chapterName').textContent=chapter;$('#chapterKicker').textContent=`CHAPTER ${String(activeChapter+1).padStart(2,'0')}`;$('#chapterTitle').innerHTML=activePage===0?chapter.replace(' ','<br>'):'';const pages=pagesFor(html);activePage=Math.max(0,Math.min(activePage,pages.length-1));$('#chapterTitle').innerHTML=activePage===0?chapter.replace(' ','<br>'):'';$('#readerCopy').innerHTML=pages[activePage];$('#readerCopyTwo').innerHTML=pages[activePage+1]||'<p>&nbsp;</p>';$('#pageProgress').textContent=`${activePage+1} / ${pages.length}`;let p=Math.round(((activeChapter+activePage/pages.length)/b.chapters.length)*100);$('#percentProgress').textContent=p+'%';$('#progressBar').style.width=p+'%';$('#tocList').innerHTML=b.chapters.map((x,i)=>`<li class="${i===activeChapter?'active':''}" data-chapter="${i}">${String(i+1).padStart(2,'0')} &nbsp; ${x}</li>`).join('');$$('#tocList li').forEach(x=>x.onclick=()=>{activeChapter=+x.dataset.chapter;activePage=0;renderChapter();closePanels()});}
function closePanels(){$('#tocPanel').classList.remove('open');$('#settingsSheet').classList.remove('open');$('#scrim').classList.remove('show')}
function nav(dir){const b=books[activeBook],html=b.content?.[activeChapter]||copy.join(''),pages=pagesFor(html),stride=innerWidth<=600?1:2,next=activePage+dir*stride;if(next>=0&&next<pages.length)activePage=next;else if(dir>0&&activeChapter<b.chapters.length-1){activeChapter++;activePage=0}else if(dir<0&&activeChapter>0){activeChapter--;activePage=Math.max(0,pagesFor(b.content?.[activeChapter]||copy.join('')).length-stride)}else return;renderChapter()}
$('#contentsButton').onclick=()=>{$('#tocPanel').classList.add('open');$('#scrim').classList.add('show')};$('#settingsButton').onclick=()=>{$('#settingsSheet').classList.add('open');$('#scrim').classList.add('show')};$('#scrim').onclick=closePanels;$$('[data-close]').forEach(x=>x.onclick=closePanels);$('#prevPage').onclick=()=>nav(-1);$('#nextPage').onclick=()=>nav(1);$('#libraryCrumb').onclick=()=>{$('#readerView').classList.add('hidden');$('#libraryView').classList.remove('hidden');$('#bookCrumb').textContent='My books'};
$('#themePicker').onclick=e=>{let b=e.target.closest('button');if(!b)return;document.body.classList.remove('theme-day','theme-night');if(b.dataset.theme!=='sepia')document.body.classList.add('theme-'+b.dataset.theme);$$('#themePicker button').forEach(x=>x.classList.toggle('selected',x===b))};$('#fontPicker').onclick=e=>{let b=e.target.closest('button');if(!b)return;let f={literata:'Literata,Georgia,serif',georgia:'Georgia,serif',charter:'Charter,Bitstream Charter,serif',helvetica:'Helvetica,Arial,sans-serif',futura:'Futura,Century Gothic,sans-serif',sans:'Segoe UI,Arial,sans-serif',mono:'Consolas,monospace'}[b.dataset.font];document.documentElement.style.setProperty('--font',f);$$('#fontPicker button').forEach(x=>x.classList.toggle('selected',x===b))};$('#alignPicker').onclick=e=>{let b=e.target.closest('button');if(!b)return;document.documentElement.style.setProperty('--align',b.dataset.align);$$('#alignPicker button').forEach(x=>x.classList.toggle('selected',x===b))};function setSize(x){textSize=Math.max(16,Math.min(26,x));document.documentElement.style.setProperty('--text-size',textSize+'px');$('#sizeSlider').value=textSize}$('#sizeSlider').oninput=e=>setSize(+e.target.value);$('#smallerText').onclick=()=>setSize(textSize-1);$('#largerText').onclick=()=>setSize(textSize+1);
$('#readerCopy').onclick=e=>{if(e.target.matches('.book-image')){$('#lightboxImage').src=e.target.src;zoomIndex=2;zoom=1;$('#lightbox').style.setProperty('--zoom',zoom);$('#lightbox').classList.add('open')}};$('#readerCopyTwo').onclick=e=>{if(e.target.matches('.book-image')){$('#lightboxImage').src=e.target.src;zoomIndex=2;zoom=1;$('#lightbox').style.setProperty('--zoom',zoom);$('#lightbox').classList.add('open')}};
$('#deleteBook').onclick=()=>{if(confirm(`Remove “${books[activeBook].title}” from your shelf?`)){books.splice(activeBook,1);renderLibrary();$('#libraryCrumb').click()}};
function readingInline(node){const copy=node.cloneNode(true);copy.querySelectorAll('*').forEach(el=>{if(!['B','STRONG','I','EM','CODE','SUP','SUB','BR','SPAN','A'].includes(el.tagName))el.replaceWith(...el.childNodes);else [...el.attributes].forEach(attr=>el.removeAttribute(attr.name))});return copy.innerHTML.trim()}
function readingHtml(doc){const excluded='nav,header,footer,aside,form,button,iframe,object,embed,canvas,script,style,link';doc.querySelectorAll(excluded).forEach(node=>node.remove());doc.querySelectorAll('[class],[id],[role]').forEach(node=>{const label=`${node.className||''} ${node.id||''} ${node.getAttribute('role')||''}`.toLowerCase();if(/\b(nav|menu|header|footer|breadcrumb|advert|share|related|comment|cookie|pagination|source|attribution)\b/.test(label))node.remove()});const selected=[...doc.body.querySelectorAll('h1,h2,h3,h4,h5,h6,p,blockquote,pre,figure,img,li')].filter(node=>!node.closest(excluded)&&!(node.matches('img')&&node.closest('figure')));for(const node of doc.body.querySelectorAll('div,section,article'))if(!node.querySelector('h1,h2,h3,h4,h5,h6,p,blockquote,pre,figure,img,li')&&node.textContent.trim())selected.push(node);selected.sort((a,b)=>a===b?0:(a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1));return selected.map(node=>{if(node.matches('img'))return node.outerHTML;if(node.matches('figure')){const image=node.querySelector('img'),caption=node.querySelector('figcaption')?.textContent.trim();return image?`<figure>${image.outerHTML}${caption?`<figcaption>${escapeHtml(caption)}</figcaption>`:''}</figure>`:''}const text=readingInline(node);if(!text)return '';if(/^\s*[\w.-]+\.(com|org|net|io|co|edu|gov)\b/i.test(text)&&text.length<40)return '';if(node.matches('h1,h2,h3,h4,h5,h6'))return `<${node.tagName.toLowerCase()}>${text}</${node.tagName.toLowerCase()}>`;if(node.matches('blockquote'))return `<blockquote>${text}</blockquote>`;if(node.matches('pre'))return `<pre>${text}</pre>`;return `<p>${text}</p>`}).filter(Boolean).join('')}
async function importEpub(file){
  try{const zip=await JSZip.loadAsync(file);const xml=await zip.file('META-INF/container.xml').async('text');const root=new DOMParser().parseFromString(xml,'application/xml').querySelector('rootfile').getAttribute('full-path');const opfText=await zip.file(root).async('text');const opf=new DOMParser().parseFromString(opfText,'application/xml');const base=root.slice(0,root.lastIndexOf('/')+1);const byId={};opf.querySelectorAll('manifest item').forEach(x=>byId[x.getAttribute('id')]=x.getAttribute('href'));const title=opf.querySelector('metadata title')?.textContent?.trim()||file.name.replace(/\.epub$/i,'');const author=opf.querySelector('metadata creator')?.textContent?.trim()||'Imported EPUB';const entries=[];
    for(const ref of opf.querySelectorAll('spine itemref')){const href=byId[ref.getAttribute('idref')];const entry=href&&zip.file(base+href);if(!entry)continue;const chapterPath=base+href,chapterDir=chapterPath.slice(0,chapterPath.lastIndexOf('/')+1);const doc=new DOMParser().parseFromString(await entry.async('text'),'text/html');for(const img of doc.querySelectorAll('img')){const src=img.getAttribute('src'),resolved=src&&decodeURIComponent(new URL(src,'https://book/'+chapterDir).pathname.slice(1)),image=resolved&&zip.file(resolved);if(!image){img.remove();continue}img.setAttribute('src',URL.createObjectURL(await image.async('blob')));img.removeAttribute('srcset');img.removeAttribute('style');img.className='book-image'}const heading=doc.querySelector('h1,h2,h3')?.textContent?.replace(/\s+/g,' ').trim()||`Chapter ${entries.length+1}`,html=readingHtml(doc);if(html)entries.push({heading,html})}
    if(!entries.length)throw new Error('No readable chapters found');books.unshift({title,author,chapters:entries.map(x=>x.heading),content:entries.map(x=>x.html)});renderLibrary();openBook(0);
  }catch(err){alert('We could not open that EPUB. Please try another non-DRM EPUB file.');console.error(err)}
}
$('#addBookButton').onclick=()=>$('#epubInput').click();$('#epubInput').onchange=e=>{let file=e.target.files[0];if(file)importEpub(file);e.target.value=''};$('#shareButton').onclick=async()=>{if(navigator.share){await navigator.share({title:'Readmore',text:'A beautiful quiet reader for EPUBs.'})}else alert('Install Readmore on your phone to share EPUB files into the reader.')};document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='Enter'){if(!e.repeat&&!$('#readerView').classList.contains('hidden'))nav(1)}if(e.key==='ArrowLeft'){if(!e.repeat&&!$('#readerView').classList.contains('hidden'))nav(-1)}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').then(async()=>{if(new URLSearchParams(location.search).has('shared')){const cache=await caches.open('shared-epubs'),response=await cache.match('./shared-book.epub');if(response)importEpub(await response.blob())}});
$('#menuButton').onclick=()=>{$('#tocPanel').classList.add('open');$('#scrim').classList.add('show')};
$('#readerCopyTwo').onclick=e=>{if(e.target.matches('.book-image')){$('#lightboxImage').src=e.target.src;zoom=1;$('#lightbox').style.setProperty('--zoom',zoom);$('#lightbox').classList.add('open')}};
let reflowTimer;addEventListener('resize',()=>{clearTimeout(reflowTimer);reflowTimer=setTimeout(()=>{if(!$('#readerView').classList.contains('hidden'))renderChapter()},120)});
const zoomLevels=[0.6,0.8,1,1.2,1.4];let zoomIndex=2;function setZoom(i){zoomIndex=Math.max(0,Math.min(zoomLevels.length-1,i));zoom=zoomLevels[zoomIndex];$('#lightbox').style.setProperty('--zoom',zoom)}
$('#lightboxImage').ondblclick=()=>{setZoom((zoomIndex+1)%zoomLevels.length)};$('#lightboxImage').addEventListener('touchend',e=>{if(e.touches&&e.touches.length===0){const now=Date.now();if(now-($('#lightboxImage').dataset.lastTap||0)<300){setZoom((zoomIndex+1)%zoomLevels.length)} $('#lightboxImage').dataset.lastTap=now}});
$('#zoomIn').onclick=()=>setZoom(zoomIndex+1);$('#zoomOut').onclick=()=>setZoom(zoomIndex-1);$('#lightbox').onclick=e=>{if(e.target===$('#lightbox')){$('#lightbox').classList.remove('open');zoomIndex=2}};
renderLibrary();
